### PR TITLE
post-game back

### PR DESCRIPTION
**Pull request by N-4-Nina**
We got carried away and this PR is way bigger than it should.
- It implements score display on frontend
- It handles the post-game
  - Backend:
    - Game actually ends when score to win is reached, and an event is sent to the frontend.
    - Users are patched for stats
    - Achievements are unlocked.
    - Matches are updated and so the status should behave normally (return to online or offline)
  - Frontend:
    - On endGame event, the game stops updating and a dialog box opens to allow user to join the main queue once more
- GameWindow changed and now lacks a way to accept challenges (next PR). It does implement a nice scrolling view to spectate IN PROGRESS games, though we do need to handle disconnection better, as some games stay in progress forever.
- GameView now displays the rules of the game.

That should be all, feel free to ask us if anything is unclear.

### CODE REVIEW

**Review by tmorris42 — COMMENTED** [review]
Small issues:

- [x] A spectator receives the message that they lost at the end of the game
- [ ] The game ends at 5 but the instructions say 11

**Comment by tmorris42** [comment]
I'm getting an error where the backend freezes after a match is completed. It doesn't seem to happen every time, but if I play several games with the same users it eventually happens. I tried with a fresh database and containers, but the issue persisted intermittently. It may (or may not) have to do with the achievements log, based on the message

```
ft_transcendence-backend-1   | 2 played  4
ft_transcendence-backend-1   | 3 played  3
ft_transcendence-backend-1   | [Nest] 42  - 10/03/2022, 11:31:46 AM     LOG [GameGateway] Terminating game 4 with status HOME
ft_transcendence-db-1        | 2022-10-03 11:31:46.628 UTC [113] ERROR:  duplicate key value violates unique constraint "UQ_a3cf15ad0420e0cd081f2b63c55"
ft_transcendence-db-1        | 2022-10-03 11:31:46.628 UTC [113] DETAIL:  Key ("achievementId", "userId")=(4, 3) already exists.
ft_transcendence-db-1        | 2022-10-03 11:31:46.628 UTC [113] STATEMENT:  INSERT INTO "achievements_log"("createdAt", "userId", "achievementId") VALUES (DEFAULT, $1, $2) RETURNING "id", "createdAt"
ft_transcendence-backend-1   | 
ft_transcendence-backend-1   | /tmp/app/src/driver/postgres/PostgresQueryRunner.ts:299
ft_transcendence-backend-1   |             throw new QueryFailedError(query, parameters, err)
ft_transcendence-backend-1   |                   ^
ft_transcendence-backend-1   | QueryFailedError: duplicate key value violates unique constraint "UQ_a3cf15ad0420e0cd081f2b63c55"
ft_transcendence-backend-1   |     at PostgresQueryRunner.query (/tmp/app/src/driver/postgres/PostgresQueryRunner.ts:299:19)
ft_transcendence-backend-1   |     at runMicrotasks (<anonymous>)
ft_transcendence-backend-1   |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
ft_transcendence-backend-1   |     at InsertQueryBuilder.execute (/tmp/app/src/query-builder/InsertQueryBuilder.ts:161:33)
ft_transcendence-backend-1   |     at SubjectExecutor.executeInsertOperations (/tmp/app/src/persistence/SubjectExecutor.ts:428:42)
ft_transcendence-backend-1   |     at SubjectExecutor.execute (/tmp/app/src/persistence/SubjectExecutor.ts:137:9)
ft_transcendence-backend-1   |     at EntityPersistExecutor.execute (/tmp/app/src/persistence/EntityPersistExecutor.ts:194:21)
```

**Comment by tmorris42** [comment]
This looks really good! I love the changes.

The only significant problem I found was the crash detailed above

**Comment by N-4-Nina** [comment]
@tmorris42 
@Mel-louie fixed the spectator message issue and I fixed the crash on duplicate log, we have a PR ready to put score to win up to 11 but we'll wait to merge it on master as it would make testing significantly longer

**Review by tmorris42 — APPROVED** [review]
Looks good!

**Pull request merged**
