### PR TITLE
A UI skeleton

### LINKED ISSUE #13: frontend: create a UI skeleton
Create a skeleton for further work with :

- a login page
- a profile page
- a game page
- a chat page
- an about page

### PR DESCRIPTION
**Pull request by fyusuf-a**
I created a UI skeleton with a bar and a navigation drawer and the following routes:

- `/profile`
- `/game`
- `/chat`
- `/about`
- `/login`

Fix #13

### CODE REVIEW

**Comment by fyusuf-a** [comment]
I fixed this issue by adding a pre-commit hook. It should work with `git` versions `>=2.9`. Can you try and see if this pre-commit hook is imported in your git repository? I am not sure if the `git` configuration would be imported in your repository.

**Comment by fyusuf-a** [comment]
I fixed this issue by adding a pre-commit hook to do the linting. Could you check that this hook comes with the repo please?

**Comment by tmorris42** [comment]
> I fixed this issue by adding a pre-commit hook to do the linting. Could you check that this hook comes with the repo please?

The hooks remain local, so they aren't run automatically, but I see that .githooks was included in the repo with your script

**Review by tmorris42 — APPROVED** [review]
Looks good!

**Pull request merged**
