### PR TITLE
feat(chat) allow owner to change password

### LINKED ISSUE #298: Owner of channel should be able to set/change password

### PR DESCRIPTION
**Pull request by tmorris42**
Owner can now change/set/unset the password from the channel settings by selecting "Set or Change password"

- If a channel is PUBLIC/PRIVATE, adding a password will make it PROTECTED with the new password
- If a channel is already PROTECTED, adding a password will change the password
- If an empty password is submitted, the channel will become PUBLIC no matter what type(s) it has been before

Fix #298

### CODE REVIEW

**Comment by Mel-louie** [comment]
When I test a chat which is protected, a user who is not in it can join it and send messages. Without to have to set a password. Is it normal for this PR?

Apart from that, the behavior for password changes works!

**Review by Mel-louie — APPROVED** [review]

**Comment by tmorris42** [comment]
> When I test a chat which is protected, a user who is not in it can join it and send messages. Without to have to set a password. Is it normal for this PR?

If you are testing with DISABLE_AUTHENTICATION=true, then that is normal. Otherwise it should prevent them from joining without the proper password

**Comment by Mel-louie** [comment]
Oh yeah, you're right!
I'm sorry, I forgot I was testing with DISABLE_AUTHENTICATION=true.
So, everything is fine :)

**Comment by tmorris42** [comment]
No problem, definitely better to check!

**Pull request merged**
